# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

workspace 'Sample2.xcworkspace'

target 'Sample2' do
  inherit! :search_paths
  project 'Sample2.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpenWeb3Lib' '1.0.6'

end
